<?xml version="1.0"?>
<robot name="kkbot"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="xacro_template.xacro"/>

    <!-- base_footprint -->
    <link name="base_footprint"/>


    <!-- base -->
    <link name="base_link">
        <xacro:cylinder_visual r="${bot_radius}" h="${bot_length}" origin_r="0" origin_p="0" origin_y="0" color="blue"/>
        <xacro:cylinder_collision r="${bot_radius}" h="${bot_length}" origin_r="0" origin_p="0" origin_y="0" color="blue"/>
        <xacro:cylinder_inertia m="0.2" r="${bot_radius}" h="${bot_length}" />
    </link>
    <xacro:joint name="base" parent_name="base_footprint" type="fixed" origin_x="0" origin_y="0" origin_z="${bot_length / 2 + wheel_radius}" axis_x="0" axis_y="0" axis_z="0" />

    <!-- laser -->
    <link name="laser_link">
        <xacro:cylinder_visual r="${laser_radius}" h="${laser_length}" origin_r="0" origin_p="0" origin_y="0" color="red"/>
        <xacro:cylinder_collision r="${laser_radius}" h="${laser_length}" origin_r="0" origin_p="0" origin_y="0" color="red"/>
        <xacro:cylinder_inertia m="0.1" r="${laser_radius}" h="${laser_length}" />
    </link>
    <xacro:joint name="laser" parent_name="base_link" type="fixed" origin_x="0" origin_y="0" origin_z="0.075" axis_x="0" axis_y="0" axis_z="0" />

    <!-- imu -->
    <link name="imu_link">
        <xacro:box_visual w="${imu_width}" d="${imu_depth}" h="${imu_heigth}" origin_r="0" origin_p="0" origin_y="0" color="green"/>
        <xacro:box_collision w="${imu_width}" d="${imu_depth}" h="${imu_heigth}" origin_r="0" origin_p="0" origin_y="0" color="green"/>
        <xacro:box_inertia m="0.1" w="${imu_width}" d="${imu_depth}" h="${imu_heigth}" />
    </link>
    <xacro:joint name="imu" parent_name="base_link" type="fixed" origin_x="0" origin_y="0" origin_z="0.02" axis_x="0" axis_y="0" axis_z="0" />

    <!-- left_wheel -->
    <link name="left_wheel_link">
        <xacro:cylinder_visual r="${wheel_radius}" h="${wheel_length}" origin_r="${pi / 2}" origin_p="0" origin_y="0" color="black"/>
        <xacro:cylinder_collision r="${wheel_radius}" h="${wheel_length}" origin_r="${pi / 2}" origin_p="0" origin_y="0" color="black"/>
        <xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_length}" />
    </link>
    <xacro:joint name="left_wheel" parent_name="base_link" type="continuous" origin_x="-0.02" origin_y="${bot_radius}" origin_z="-${bot_length / 2}" axis_x="0" axis_y="1" axis_z="0" />

    <!-- right_wheel -->
    <link name="right_wheel_link">
        <xacro:cylinder_visual r="${wheel_radius}" h="${wheel_length}" origin_r="${pi / 2}" origin_p="0" origin_y="0" color="black"/>
        <xacro:cylinder_collision r="${wheel_radius}" h="${wheel_length}" origin_r="${pi / 2}" origin_p="0" origin_y="0" color="black"/>
        <xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_length}" />
    </link>
    <xacro:joint name="right_wheel" parent_name="base_link" type="continuous" origin_x="-0.02" origin_y="-${bot_radius}" origin_z="-${bot_length / 2}" axis_x="0" axis_y="1" axis_z="0" />

    <!-- caster -->
    <link name="caster_link">
        <xacro:sphere_visual r="${caster_radius}" origin_r="0" origin_p="0" origin_y="0" color="white"/>
        <xacro:sphere_collision r="${caster_radius}" origin_r="0" origin_p="0" origin_y="0" color="white"/>
        <xacro:sphere_inertia m="0.02" r="${caster_radius}" />
    </link>
    <xacro:joint name="caster" parent_name="base_link" type="fixed" origin_x="0.06" origin_y="0" origin_z="-${bot_length / 2 + caster_radius}" axis_x="0" axis_y="1" axis_z="0" />
</robot>